### ISSUE TITLE
 warning on console

### ISSUE THREAD

**Issue by luabraggion** [P4sca1/nuxt-headlessui#17]
![Captura de tela 2022-11-30 171023](https://user-images.githubusercontent.com/77340549/204898649-71fff294-f19c-446a-83fe-a674cf534eb1.png)

it's giving a warning on the console, I'm using nuxt 3, I've already added the parameter below to my nuxt.config.ts and still the warning.

build: {
        analyze: true,
        transpile: ['@headlessui/vue']
   }

**Comment by P4sca1** [comment]
I'm pretty sure the warning does not originate from this module.
