### ISSUE TITLE
Add note to documentation about hydration issues with SSR for Dialog component

### ISSUE THREAD

**Issue by SvenWesterlaken** [P4sca1/nuxt-headlessui#18]
I had a hydration error in my local environment while using this library. After some digging, I found this thread https://github.com/tailwindlabs/headlessui/issues/1496 where they basically said that you should wrap the Dialog component in a `<client-only>` tag.  It makes sense (and fixed my problem), but I would suggest adding this to the readme so other people could easily take note of this.

**Comment by P4sca1** [comment]
Hey @SvenWesterlaken, with the next release, all Popover, Dialog, and Portal components will be client only by default. No need to wrap them in `<ClientOnly>`.
