### ISSUE TITLE
Disclosure component hydration missmatch

### ISSUE THREAD

**Issue by gkkirilov** [P4sca1/nuxt-headlessui#40]
![image](https://github.com/P4sca1/nuxt-headlessui/assets/8720012/7c500f6c-5749-4554-ae71-6eac27ed736b)
Wrapping it in ClientOnly fixes it but will be better if the generated id matches and the component is rendered server side.

```

<Disclosure v-slot="{ open }">
    <DisclosureButton
      class="row text-center w-full flex items-center m-0 py-2"
    >
    Button
      <div class="col-md-1 justify-end flex">
        <ChevronUpIcon
          :class="!open ? 'rotate-180 transform' : ''"
          class="h-7 w-7 text-sky-800 self-center flex"
        />
      </div>
    </DisclosureButton>
      <DisclosurePanel
        class="text-gray-500 py-2 text-center"
      >
      Expanded content
      </DisclosurePanel>
  </Disclosure>
  
```

**Comment by P4sca1** [comment]
This is an upstream issue. Please see https://github.com/tailwindlabs/headlessui/issues/2913.

**Comment by vanling** [comment]
@P4sca1  https://github.com/tailwindlabs/headlessui/issues/2913#issuecomment-1924681165 could this fix by @reinink work?

<script setup>
import { Switch } from '@headlessui/vue'

provide('headlessui.useid', () => useId('myapp-'))
</script>
