### ISSUE TITLE
Error: provideHeadlessUseId(() => useId());

### ISSUE THREAD

**Issue by IzakJackson** [P4sca1/nuxt-headlessui#49]
I get this error: 500 useId is not defined

When using: provideHeadlessUseId(() => useId()); in app.vue

```
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>

<script setup lang="ts">
provideHeadlessUseId(() => useId());
</script>
```

**Comment by P4sca1** [comment]
Which version of nuxt are you using? Nuxt Version 3.10.0 or newer is required for the useId() composable.

**Comment by IzakJackson** [comment]
I was on 3.9.2 and just updated to latest. All working now, but it appears I'm still getting hydration errors:

```
[Warning] warn [Vue warn]: Hydration attribute mismatch on (135) (browser.mjs, line 44)
  - rendered on server: id=\"headlessui-radiogroup-option-nE3KxD8SGyR-8\"
  - expected on client: id=\"headlessui-radiogroup-option-9\"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch."
```

**Comment by P4sca1** [comment]
Interesting. Did you try restarting nuxt and clearing the website cache? If the problem still persists, could you share a reproduction please?

**Comment by agracia-foticos** [comment]
Same issue!

**Comment by P4sca1** [comment]
@agracia-foticos Please provide a reproduction, so that I can debug the issue.

**Comment by agracia-foticos** [comment]
> @agracia-foticos Please provide a reproduction, so that I can debug the issue.

@P4sca1 here you are
https://stackblitz.com/edit/nuxt-starter-zc7r2b

**Comment by agracia-foticos** [comment]
@P4sca1 any advance?

**Comment by agracia-foticos** [comment]
> @agracia-foticos You forgot to actually provide the id. Add the following to your `app.vue` file:
> 
> ```
> <script setup lang="ts">
>   provideHeadlessUseId(() => useId())
> </script>
> ```
> 
> Some things to consider:
> 
> * Ensure you are using a signle root element. See [fix(nuxt): useId() causing hydration-error when using value multiple times nuxt/nuxt#26315](https://github.com/nuxt/nuxt/pull/26315).
> * Using `LazyHeadlessPopover` does not work. Use `HeadlessPopover` instead. This might apply to other components too. You will get a hydration missmatch where the id often looks similar, but uses a `_` instead of a `-` for example. See [`useId` hydration mismatch when used in a dynamic global component nuxt/nuxt#27378](https://github.com/nuxt/nuxt/issues/27378).

I remove Lazy and use the composable and works

**Comment by agracia-foticos** [comment]
@P4sca1 

I added to the project a DelayHydration https://github.com/johannschopplich/nuxt-vitalizer?tab=readme-ov-file#delayhydration and raises again the error

Please check
https://stackblitz.com/edit/nuxt-starter-zc7r2b

**Comment by P4sca1** [comment]
I don't think that this is an issue with `nuxt-headlessui` and I can't provide support for third-party libraries. Please open an issue at their repository.

**Comment by agracia-foticos** [comment]
> I don't think that this is an issue with `nuxt-headlessui` and I can't provide support for third-party libraries. Please open an issue at their repository.

Thanks, i open the issue to nuxt vitalizer! Regards

**Comment by agracia-foticos** [comment]
@P4sca1 https://github.com/johannschopplich/nuxt-vitalizer/issues/3#issuecomment-2219673068 can you do anything with this comment??? Thanks in advance :)

**Comment by P4sca1** [comment]
Not before the issues with ID generation are resolved. Maybe Vue 3.5 will help here, as it is rumored to contain a native useId hook.

**Comment by agracia-foticos** [comment]
> Not before the issues with ID generation are resolved. Maybe Vue 3.5 will help here, as it is rumored to contain a native useId hook.

I wait for Vue 3.5, thanks!!! :)

**Comment by agracia-foticos** [comment]
@P4sca1 https://github.com/nuxt/nuxt/pull/28285 can you upgrade this module??? :D

**Comment by P4sca1** [comment]
> @P4sca1 [nuxt/nuxt#28285](https://github.com/nuxt/nuxt/pull/28285) can you upgrade this module??? :D

There is nothing that needs to be changed in this module. Your existing code continues to work.
When you upgrade nuxt it will use `useId` from `vue` instead of the custom implementation.
`@headlessui/vue` could update their code to use `useId` from `vue` if no custom function was provided. That way `provideHeadlessUseId` would no longer be needed.

**Comment by P4sca1** [comment]
See https://github.com/tailwindlabs/headlessui/discussions/3457

**Comment by P4sca1** [comment]
If you upgrade vue to 3.5.0 or newer and `@headlessui/vue` to 1.7.23 or newer, `nuxt-headlessui` will automatically use the native `useId` function provided by vue. There is no need to update `nuxt-headlessui`. You can remove `provideHeadlessUseId()` from your `app.vue` function. If you keep it, it will just do nothing.

**Comment by agracia-foticos** [comment]
@P4sca1 i upgrade headless ui and vue 3.5.0 but this console.error persists. any idea?
![image](https://github.com/user-attachments/assets/31cde602-71b4-414c-a40c-df87be32e8b9)

**Comment by P4sca1** [comment]
@agracia-foticos Ensure you also use the latest version of nuxt an maybe regenerate your lock file, to avoid having multiple versions of vue installed. If the issue persists, please provide a reproduction.

**Comment by agracia-foticos** [comment]
@P4sca1  here you are a reproduction
https://stackblitz.com/edit/nuxt-starter-zc7r2b

with  "nuxt": "3.13.1",
    "vue": "3.5.4",
and  "nuxt-headlessui": "^1.2.0"

**Comment by MarijnFK** [comment]
I think same problem, but from NuxtUI (using ULandingFAQ). Hydration error comes from DisclosureButton

**Comment by P4sca1** [comment]
> @P4sca1 here you are a reproduction https://stackblitz.com/edit/nuxt-starter-zc7r2b
> 
> with "nuxt": "3.13.1", "vue": "3.5.4", and "nuxt-headlessui": "^1.2.0"

`npm why @headlessui/vue` reveals that you are using `v1.7.22`. Native `useId` support got introduced in `v1.7.23`. Once you upgrade the dependency, it should work.



> I think same problem, but from NuxtUI (using ULandingFAQ). Hydration error comes from DisclosureButton

Please also check if you are using the latest dependency versions. If the problem persists, please provide a reproduction.

**Comment by MarijnFK** [comment]
turns out i was using a component with headless components and a ```useAsyncData``` in the setup, but didn't have ```await useAsyncData```.  Therefor the count was wrong.

**Comment by dochoss** [comment]
Came across this error getting the plugin set up.  I'm getting these errors for `Dialog` and `DialogPanel` in the browser:

```
Failed to resolve component: Dialog
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

I've followed the instructions here, and am using this for my devDependencies:

```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/image": "^1.10.0",
    "@nuxtjs/tailwindcss": "^6.14.0",
    "nuxt": "^3.17.3",
    "nuxt-headlessui": "^1.2.0",
    "nuxt-icon": "^0.6.10"
  }
}
```

When I run `npm why @headlessui/vue` I get this response:

```
@headlessui/vue@1.7.23 dev
node_modules/@headlessui/vue
  @headlessui/vue@"^1.7.18" from nuxt-headlessui@1.2.0
  node_modules/nuxt-headlessui
    dev nuxt-headlessui@"^1.2.0" from the root project
```

So @headlessui/vue is still at v1.7.18 in the tree somehow.  I've deleted the node_modules folder and package-lock.json, but the issue persists.  Any help for what I may be doing wrong?  

Disclaimer: I'm not a super expert in the npm ecosystem, but am a reasonably competent developer, so I'm happy to dig where needed!  :)
